name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['24.0', '23.3', '22.3', '21.3']
    runs-on: 'ubuntu-20.04'
    env:
      OTPVER: ${{ matrix.otp }}
    steps:
      - uses: actions/checkout@v2
      - uses: ErlGang/setup-erlang@v1.0.0
        with:
          otp-version: ${{ matrix.otp }}
      - run: make rebar3
      - run: make
      - run: make test
      - run: make dialyzer
        if: ${{ matrix.otp == '24.0' }}
      - run: make codecov
        if: ${{ matrix.otp == '24.0' }}
      - run: pip install --user codecov
        if: ${{ matrix.otp == '24.0' }}
      - run: /home/runner/.local/bin/codecov
        if: ${{ matrix.otp == '24.0' }}
